Feature/footer
Oleg1front/project-group-21 pull request #3
Opened 2024-02-08 23:20 UTC by Liubov-Pysana

The footer is done for all media types. Still need to add effects (hover).

2024-02-09 06:10 UTC, Oleg1front commented on src/partials/footer.html
> +      <div class="footer-navigation">
навігація у футері має бути обернута в тег nav

2024-02-09 06:42 UTC, Oleg1front requested changes
В цілому дуже добре, але треба з index.html прибрати свої шрифти та підключення modern-normalize, і передивись будь ласка марджини між боді там секцією, на макеті вони менші, також треба додати єфекти ховера на кнопки та посилання на соц мережі, і в самі посилання на соц мережі потрабно додати посилання на  реальні соц мережі. також в html файлі потрібно навігацію у футері реалізувти через тег nav.
![Screenshot_8](https://github.com/Oleg1front/project-group-21/assets/151941470/7a058db2-4503-47be-bae0-4cef9ccf50da)

2024-02-10 02:06 UTC, Liubov-Pysana commented
Привіт, дякую за правки.

Ти міг би уточнити щодо цих 3х пунктів:
1) "треба з index.html прибрати свої шрифти" та "підключення
modern-normalize" - я в індексі нічого не мала би додавати, працюю лише з
файлом footer.html.
2) "передивись будь ласка марджини між боді там секцією, на макеті вони
менші" - мені було б легше, якби ти міг скрінами показати, що саме маєш на
увазі. На рахунок маржинів між боді та секцією - ти про падінг лефт і райт?
Бо я, ніби, між вертикальними секціями маржини не ставила.

Наперед дуже дякую, і продуктивних вихідних))


On Fri, 9 Feb 2024 at 06:42, Oleh Liubimov ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> В цілому дуже добре, але треба з index.html прибрати свої шрифти та
> підключення modern-normalize, і передивись будь ласка марджини між боді там
> секцією, на макеті вони менші, також треба додати єфекти ховера на кнопки
> та посилання на соц мережі, і в самі посилання на соц мережі потрабно
> додати посилання на реальні соц мережі. також в html файлі потрібно
> навігацію у футері реалізувти через тег nav.
> Screenshot_8.png (view on web)
> <https://github.com/Oleg1front/project-group-21/assets/151941470/7a058db2-4503-47be-bae0-4cef9ccf50da>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Oleg1front/project-group-21/pull/3#pullrequestreview-1871748416>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BCPY5AIGS3K2HZQHF5QZLRDYSXAODAVCNFSM6AAAAABDASUWHGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQNZRG42DQNBRGY>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2024-02-10 15:11 UTC, Oleg1front requested changes
перенести ховер з медіа запиту в основний текст коду, змінити колір кнопок при ховері,  і треба адаптувати футер під 320рх, від 320 до 375 він має бути гумовим, а далі так як вже зроблено

2024-02-12 09:33 UTC, Oleg1front approved these changes
ok

2024-02-12 10:06 UTC, merged